version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: workout_partner_postgres
    environment:
      POSTGRES_DB: workout_partner_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: workout_partner_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: workout_partner_adminer
    ports:
      - "8082:8080"
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:

